title: Sanjana Anuradha
#logo: /assets/img/headshot_circle.png
Contact
11, Mapesbury Road, Kilburn, 
London. NW2 4HX
(+44) 7984 720 460
Email: sanjana.benthara@gmail.com
LinkedIn: Sanjana Anuradha
Web: https://92benthara.github.io/

show_downloads: true
theme: jekyll-theme-minimal
